Repository Rchicken/CheckMoi-v2, pull requests merged in 2022-10, with the labels that each got.

#10 chore: swagger setting
  build.gradle
  src/main/java/com/rchicken/checkmoi2/global/HealthApi.java
  src/main/resources/application.yml
Labels: doc, chore

#12 11 CI/CD 파이프라인 구성
  .github/workflows/build.yaml
  .github/workflows/deploy-main.yaml
  build.gradle
  gradlew
Labels: chore

#17 chore : 배포 스크립트 및 도커 컴포즈 파일 추가
  docker/docker-compose.yaml
  script/deploy.sh
Labels: chore

#21 feat: add swagger config
  build.gradle
  src/main/java/com/rchicken/checkmoi2/global/config/CorsConfig.java
  src/main/java/com/rchicken/checkmoi2/global/config/SwaggerConfig.java
  src/main/java/com/rchicken/checkmoi2/global/config/props/SwaggerProps.java
  src/main/java/com/rchicken/checkmoi2/global/config/props/SwaggerServer.java
  src/main/resources/application-swagger.yml
  src/main/resources/application.yml
Labels: doc

#26 feat: base entity
  build.gradle
  src/main/java/com/rchicken/checkmoi2/global/model/BaseEntity.java
Labels: feat

#31 chore : 공통 응답 객체 포맷 추가
  src/main/java/com/rchicken/checkmoi2/global/HealthApi.java
  src/main/java/com/rchicken/checkmoi2/global/model/SuccessResponse.java
Labels: chore, review
